server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lear1?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath*:sql/*.sql
      data-locations: classpath*:sql/data/*.sql

